### ISSUE TITLE
需要加一个isFunction的判断

### ISSUE THREAD

**Issue by zwgdrs** [drawcall/inkpaint#1]
https://github.com/drawcall/inkpaint/blob/c26e68bd359e5e804aae8f9d99e6fc8f1456f4fb/src/display/Container.js#L233

我在使用inkpaint进行创建text元素的时候，在一些场景下会因为该函数属性为undefined而报错，保险起见，建议在这里判断一下child是否存在renderWebGL方法

**Comment by drawcall** [comment]
Welcome to submit a pr
