### ISSUE TITLE
示例中sprite下的video示例报错无法跑通

### ISSUE THREAD

**Issue by zwgdrs** [drawcall/inkpaint#2]
https://github.com/drawcall/inkpaint/blob/c26e68bd359e5e804aae8f9d99e6fc8f1456f4fb/examples/source/js/sprite/video.js#L30

提示没有这个方法

**Comment by drawcall** [comment]
Server side does not support direct analysis of media, refer to this https://github.com/tnfe/FFCreator/blob/master/lib/node/video.js
